language: ruby
rvm:
 - "2.2.3"

services:
  - mongodb
  - redis-server

env:
  - TRAVIS_NODE_VERSION="5.0.0"

install:
  # Install a newer version of node than Travis has, in order to run jsdom
  - wget -P /tmp http://nodejs.org/dist/v$TRAVIS_NODE_VERSION/node-v$TRAVIS_NODE_VERSION-linux-x64.tar.xz
  - mkdir ~/nodejs
  - tar -C ~/nodejs --strip-components 1 -xf /tmp/node-v$TRAVIS_NODE_VERSION-linux-x64.tar.xz
  - export PATH=~/nodejs/bin:$PATH
  - which node
  - node --version
  - npm install
  # Ruby dependencies as per usual
  - bundle install --deployment --path=${BUNDLE_PATH:-vendor/bundle}

script:
  # API tests
  - bundle exec rspec spec
  # Admin tests
  - cd admin && bundle exec rspec spec && cd ..
  # Frontend tests
  - npm test
  # Ruby linter
  - bundle exec rubocop
  # Coffeescript linter
  - npm run lint

after_script:
  # Update http://coveralls.io with the test coverage of both ruby and coffeescripts
  - bundle exec rake coveralls:push
